import "./globals.css";
import Container from "@mui/material/Container";
import { ReduxProvider } from "@/store/provider";
import Footer from "@/components/layout/footer";
import Navbar from "@/components/layout/navbar";
import ThemeRegistry from "@/components/themeRegistry";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body>
        <Container maxWidth="lg" sx={{ mb: 6 }}>
          <ThemeRegistry>
            <ReduxProvider>
              <Navbar />
              {children}
              <Footer />
            </ReduxProvider>
          </ThemeRegistry>
        </Container>
      </body>
    </html>
  );
}
