import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import Container from "@mui/material/Container";
import { ReduxProvider } from "@/store/provider";
import Footer from "@/components/layout/footer";
import Navbar from "@/components/layout/navbar";
import ThemeRegistry from "@/components/themeRegistry";
import { ToastContainer } from "react-toastify";
import EducationBanner from "@/components/common/EducationBanner";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Container maxWidth="lg" sx={{ mb: 10 }} disableGutters>
          <ReduxProvider>
            <ThemeRegistry>
              <Navbar />
              {children}
              <Footer />
              <ToastContainer autoClose={1500} hideProgressBar />
              <EducationBanner />
            </ThemeRegistry>
          </ReduxProvider>
        </Container>
      </body>
    </html>
  );
}
